version: 2
jobs:
  bundler_dependencies:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      - run:
          name: install bundler
          command: gem install bundler:2.1.4
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle check || bundle install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

  yarn_dependencies:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-dependencies-{{ checksum "yarn.lock" }}
            - v1-yarn-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-yarn-dependencies-{{ checksum "yarn.lock" }}

  build_assets:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - v1-yarn-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: install bundler
          command: gem install bundler:2.1.4
      - run: yarn install --frozen-lockfile
      - run: bundle check || bundle install
      - run: bin/rails webpacker:compile
      - run: env RAILS_ENV=test bin/rails webpacker:compile
      - persist_to_workspace:
          root: .
          paths:
            - public/packs-test
            - public/packs

  test:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          DATABASE_URL: postgres://postgres@localhost
          PARALLEL_WORKERS: 4
      - image: circleci/postgres:11.5-ram
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: install prereqs
          command: sudo apt-get update && sudo apt-get install -y gsfonts
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - v1-yarn-dependencies-{{ checksum "yarn.lock" }}
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: install bundler
          command: gem install bundler:2.1.4
      - run: yarn install --frozen-lockfile
      - run: bundle check || bundle install
      - run: bundle exec rake db:test:prepare
      - run:
          name: run tests
          command: |
            bundle exec rails test
      - store_test_results:
          path: ~/repo/test/reports

  test_system:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          DATABASE_URL: postgres://postgres@localhost
          PARALLEL_WORKERS: 1
          HEADLESS: 1
      - image: circleci/postgres:11.5-ram
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: install prereqs
          command: sudo apt-get update && sudo apt-get install -y gsfonts
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - v1-yarn-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: install bundler
          command: gem install bundler:2.1.4
      - run: yarn install --frozen-lockfile
      - run: bundle check || bundle install
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake db:test:prepare
      - run:
          name: run system tests
          command: |
            bundle exec rails test:system
      - store_artifacts:
          path: ~/repo/tmp/screenshots
          destination: test-screenshots
      - store_test_results:
          path: ~/repo/test/reports

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Development to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git development:master

workflows:
  version: 2
  build_and_test:
    jobs:
      - bundler_dependencies
      - yarn_dependencies
      - build_assets:
          requires:
            - bundler_dependencies
            - yarn_dependencies
      - test:
          requires:
            - build_assets
      - test_system:
          requires:
            - build_assets
      # - deploy:
      #     requires:
      #       - test
      #       - test_system
      #     filters:
      #       branches:
      #         only: development
