version: 2
jobs:
  bundler_dependencies:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      - run:
          name: install bundler
          command: gem install bundler:2.0.2
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle check || bundle install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

  yarn_dependencies:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  build_assets:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install bundler
          command: gem install bundler:2.0.2
      - run: bundle check || bundle install
      - run: bin/rails webpacker:compile
      - persist_to_workspace:
          root: .
          paths:
            - public/packs-test

  test:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          DATABASE_URL: postgres://postgres@localhost
      - image: circleci/postgres:11.5-ram
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: install prereqs
          command: sudo apt-get update && sudo apt-get install -y gsfonts
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: install bundler
          command: gem install bundler:2.0.2
      - run: bundle check || bundle install
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run:
          name: run tests
          command: |
            bundle exec rails test

  test_system:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          DATABASE_URL: postgres://postgres@localhost
          HEADLESS: 1
      - image: circleci/postgres:11.5-ram
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: install prereqs
          command: sudo apt-get update && sudo apt-get install -y gsfonts
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install bundler
          command: gem install bundler:2.0.2
      - run: bundle check || bundle install
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run:
          name: run system tests
          command: |
            bundle exec rails test:system
      - store_artifacts:
          path: ~/repo/tmp/screenshots
          destination: test-screenshots

workflows:
  version: 2
  build_and_test:
    jobs:
      - bundler_dependencies
      - yarn_dependencies
      - build_assets:
          requires:
            - bundler_dependencies
            - yarn_dependencies
      - test:
          requires:
            - build_assets
      - test_system:
          requires:
            - build_assets